tools-2661 change module path to github.com/aerospike/asconfig
aerospike/asconfig pull request #17
Opened 2023-09-18 18:42 UTC by dwelch-spike

2023-09-18 18:45 UTC, dwelch-spike commented
The purpose of these changes is to make getting sub packages of asconfig easier.
like `go get http://github.com/aerospike/asconfig/asconf` .

2023-09-20 00:31 UTC, jdogmcsteezy requested changes

2023-09-20 00:31 UTC, jdogmcsteezy commented on README.md
> +git clone https://github.com/github.com/aerospike/asconfig.git
```suggestion
git clone https://github.com/github.com/aerospike/asconfig.git
```

This does not look right

2023-09-20 00:31 UTC, jdogmcsteezy commented on README.md
> +git clone https://github.com/github.com/aerospike/asconfig.git
same

2023-09-20 00:31 UTC, jdogmcsteezy commented on .github/workflows/draft-release.yml
> +    uses: github.com/aerospike/asconfig/.github/workflows/snyk-test.yml@main
I don't think these need to be changed

2023-09-20 17:35 UTC, dwelch-spike commented on README.md
> +git clone https://github.com/github.com/aerospike/asconfig.git
Ooops, replace errors, good catch!

2023-09-20 17:35 UTC, dwelch-spike commented on README.md
> +git clone https://github.com/github.com/aerospike/asconfig.git
changed

2023-09-20 17:35 UTC, dwelch-spike commented on .github/workflows/draft-release.yml
> +    uses: github.com/aerospike/asconfig/.github/workflows/snyk-test.yml@main
replace error, changed

2023-09-20 19:55 UTC, jdogmcsteezy approved these changes
LGTM

2023-09-20 23:30 UTC, merged